# Generated by Django 3.0.8 on 2020-07-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='door_num',
            field=models.CharField(default='0-0-0-0', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mandal',
            field=models.CharField(default='chejerla', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(default='524341', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='village',
            field=models.CharField(default='chittaluru', max_length=200),
        ),
    ]
