# Generated by Django 3.0.8 on 2020-08-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enduser', '0002_auto_20200731_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(default=524341),
        ),
    ]
