# Generated by Django 3.0.8 on 2020-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('newsadmin', 'newsadmin'), ('manager', 'manager'), ('paperboy', 'paperboy'), ('enduser', 'enduser')], default='enduser', max_length=10),
        ),
    ]
