# Generated by Django 3.0.8 on 2020-07-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='language',
            field=models.CharField(default='Telugu', max_length=100),
        ),
    ]
