# Generated by Django 3.0.8 on 2020-07-31 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0002_newspaper_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='language',
            field=models.CharField(default='Telugu', max_length=100),
        ),
    ]
