# Generated by Django 3.0.8 on 2020-08-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsadmin', '0003_magazine_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='magazine_type',
            field=models.CharField(choices=[('weekly', 'weekly'), ('monthly', 'monthly')], max_length=10),
        ),
    ]
