# Generated by Django 3.0.8 on 2020-07-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperBoy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pno', models.CharField(max_length=10)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsadmin.Branch')),
            ],
        ),
    ]
