# Generated by Django 3.0.8 on 2020-07-31 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paperboy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperboy',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paperboy', to=settings.AUTH_USER_MODEL),
        ),
    ]
