# Generated by Django 3.0.8 on 2020-07-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperboy', '0003_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='status',
            field=models.CharField(default='Deliveried', max_length=10),
        ),
    ]
