# Generated by Django 3.0.8 on 2020-08-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paperboy', '0006_deliverystatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperboy',
            name='pincode',
            field=models.CharField(default=524341, max_length=6),
        ),
    ]
